version: '3'
services:
  torproxy:
    image: "znetstar/tor-router"
    ports:
      - "10000:10000"
    entrypoint: "tor-router -j 30 -h 10000"
    restart: always
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  web:
    build: ./api
    ports:
     - "80:80"
    depends_on:
     - redis
    restart: always
  crawler:
    build: ./crawler
    depends_on:
      - redis
      - torproxy
    restart: always
